### ISSUE TITLE
Security concern -> need to bump 'github.com/docker/docker' version

### ISSUE THREAD

**Issue by shkleinik** [dhui/dktest#4]
**Is your feature request related to a problem? Please describe.**
This repo currently depends on an old and vulnerable `github.com/docker/docker` version: https://www.sourceclear.com/vulnerability-database/libraries/github-com-docker-docker/GO/GO/lid-886114/versions/v0.7.3

https://github.com/dhui/dktest/blob/master/go.mod#L8

**Describe the solution you'd like**
Update to the non-vulnerable version (currently it is `1.13.1`) by running:
`go get -u github.com/docker/docker`

**Comment by dhui** [comment]
Thanks for reporting the issue!
It's fixed in [v0.3.2](https://github.com/dhui/dktest/releases/tag/v0.3.2).

FYI, the docker golang library is a mess and doesn't work well with modules.
You'll have to ignore the stated tag in `go.mod`. e.g. the previously [pinned version](https://github.com/moby/moby/commit/2b7e084dc98b) was not [v0.7.3](https://github.com/moby/moby/releases/tag/v0.7.3)
Likewise, the newly [pinned version](https://github.com/moby/moby/commit/31a86c4ab209)
is not `v1.4.2`

**Comment by shkleinik** [comment]
Thanks a lot for quickly addressing this issue! I really appreciate it ^_^!
